database:
  user: ""
  password: ""
  name: ""
  host: ""
  port: ""
  sslmode: "disable"
  retry_count: 5
  retry_delay: 2s

telegram:
  token: ""
  office_tz: "Europe/Moscow" # time.LoadLocation
  group_chat_id: ""
  admin_id: ""
  notifier_config: "0 9 * * *"
  role_cache_ttl: 30m
  # notifier_config: "44 13 * * *"
  # notifier_config: "*/2 * * * *"
