database:
  user: ""
  password: ""
  name: ""
  host: ""
  port: ""
  sslmode: "disable"
  retry_count: 5
  retry_delay: 2s

telegram:
  token: ""
  office_tz: "Europe/Moscow"
  group_chat_id: ""
  admin_id: ""
  notifier_config: "0 0 9 * * *"